languaje: node_js
node_js:
    - "7"
install:
    - npm install
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: 89163141c1b622ae9977c4ed66e9e900677b8e15
    project_name: web
    localdir: build/web
    name: travisCI
    on:
        branch: prototype-react
        repo: Codents/web
