languaje: node_js
node_js:
    - "7"
install:
    - npm install
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    project_name: web
    localdir: build
    name: travisCI
    on:
        branch: prototype-react
        repo: Codents/web
