languaje: node_js
node_js:
    - "7"
install:
    - npm install
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: de17f1223298d09c167982655fcbbad4c0b4e2fb
    localdir: build/web
    name: travisCI
    on:
        branch: prototype-react
        repo: Codents/web
