languaje: node_js
node_js:
    - "7"
addons:
  chrome: stable
install:
    - node -v
    - npm -v
    - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    #- npm run test
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    project_name: web
    local_dir: build/web
    name: travisCI
    on:
        branch: prototype-react
        repo: Codents/web
